version: '3.8'

services:
  lctaz-custom:
    image: lctaz-custom:latest
    container_name: lctaz-custom
    ports:
      - "7788:7788"
    volumes:
      - lctaz-data:/app/backend/data
    restart: unless-stopped

volumes:
  lctaz-data:
